### ISSUE TITLE
controllare l overfitting del random forest

### ISSUE THREAD

**Issue by StefSeSi** [Kubasinska/SimAnn#4]
visti alla veloce su internet:
    n_estimators: The more trees, the less likely the algorithm is to overfit. ...
    max_features: You should try reducing this number. ...
    max_depth: This parameter will reduce the complexity of the learned models, lowering over fitting risk.
    min_samples_leaf: Try setting these values greater than one.

direi pure di provare una cross validation ma sempre c'è il problema che le y variano poco (al 90% stabili intorno a un valore) ... si potrebbe agirare con delle partizioni di crossvalidation "ritoccate": ben variate sulla y (...)

**Comment by ambitious-octopus** [comment]
Thank you, I will directly implement a Grid_search.
